### ISSUE TITLE
Config giving error when Config loader is created while nothing is going wrong

### ISSUE THREAD

**Issue by jonesy-b-dev** [Luke-Creative-Media/StellarEngine#14]
When starting the engine `Error parsing config file: config/BaseEngine.ini` is printed which comes from creating the ConfigLoader in the application, nothing is going wrong so idk why its printing it.

Needs some investigation

**Comment by Lukevdb01** [comment]
The issue has been resolved! The problem we encountered occurred when the application wrote to the config, creating a new empty line that led to an error during parsing.
